In [1]:
import torch

In [2]:
features = torch.randn((1,5)) # 1 row and five columns in normal distribution of mean 0 and std 1 (features x1)
features

tensor([[ 0.3798, -1.1108,  0.2831, -1.0143,  1.3761]])

In [3]:
weights = torch.randn_like(features) # having same of features and with normal distribution( weights w1)
weights

tensor([[-0.2016,  0.5824, -1.2708, -1.1295,  0.3991]])

In [4]:
bias = torch.randn((1,1)) # bias b
bias

tensor([[0.4813]])

In [5]:
# y = fsum((x1*w1)+b) # x1 and w1 is dot product

In [6]:
# f is activation function 

In [7]:
def activation(x):
  return 1/(1+torch.exp(-x)) # sigmoid

In [8]:
torch.exp(-features)

tensor([[0.6840, 3.0369, 0.7535, 2.7575, 0.2526]])

In [17]:
dotproduct = torch.mm(features,weights.view(5,1))
dotproduct



tensor([[0.6116]])

In [18]:
bias

tensor([[0.4813]])

In [19]:

linear_combination = dotproduct+bias

In [20]:
linear_combination

tensor([[1.0929]])

In [21]:
activation(linear_combination)

tensor([[0.7489]])

In [22]:
#Summary

"""Features-(1,5)
weights - (5,1),
bias - (1,1)

dot product of features and wieght = (1,1)
add dot product and bias 
apply activation on those sum 
this for single neuron"""

'Features-(1,5)\nweights - (5,1),\nbias - (1,1)\n\ndot product of features and wieght = (1,1)\nadd dot product and bias \napply activation on those sum \nthis for single neuron'

In [25]:
torch.manual_seed(7) # the things should be predictable

In [26]:
input_size = features.shape[1]
n_hidden = 2
n_outputs = 2

w1 = torch.randn(input_size,n_hidden)
w2 = torch.randn(n_hidden,n_outputs)

b1 = torch.randn((1,n_hidden))
b2 = torch.randn((1,n_outputs))

In [30]:
h1 = activation(torch.mm(features,w1)+b1)
h1.shape

torch.Size([1, 2])

In [31]:
output = activation(torch.mm(h1,w2)+b2)
output

tensor([[0.9386, 0.5927]])

In [32]:
"""Summary
2 neuron, 1 input layer(1,5), 1 hiddenlayer(2 neuron), 1 output layer(2 output)
"""

'Summary\n2 neuron, 1 input layer(1,5), 1 hiddenlayer(2 neuron), 1 output layer(2 output)\n'

In [33]:
# number of hidden units are hyperparameters

In [34]:
#Numpy vs torch

In [35]:
import numpy as np

In [36]:
a = np.random.randn(1,5)
a

array([[ 0.89633617, -2.05804165,  0.32461423,  1.22403199, -0.2633265 ]])

In [37]:
id(a)

140094298732464

In [38]:
b = torch.from_numpy(a)
b

tensor([[ 0.8963, -2.0580,  0.3246,  1.2240, -0.2633]], dtype=torch.float64)

In [39]:
id(b)

140094298735472

In [40]:
b.numpy()

array([[ 0.89633617, -2.05804165,  0.32461423,  1.22403199, -0.2633265 ]])

In [43]:
b.mul_(2)

tensor([[ 1.7927, -4.1161,  0.6492,  2.4481, -0.5267]], dtype=torch.float64)

In [44]:
a

array([[ 1.79267235, -4.1160833 ,  0.64922847,  2.44806398, -0.52665299]])

In [45]:
" In numpy to torch and torch modifications will reflect on numpy means memory sharing "

' In numpy to torch and torch modifications will reflect on numpy means memory sharing '